development:  
  adapter: postgresql
  encoding: unicode
  database: vidroo_database
  pool: 5
  username: postgres
  password: postgres

test:  
  adapter: postgresql
  encoding: unicode
  database: vidroo_test_database
  pool: 5
  username: postgres
  password: postgres