# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bffe69cf2752a2e0bb7a727693ed529b89eacaf23d715969eedb91f4c220a14cfbfa2cb5b3c4c758294441e04091d3de8f3ce7ae0c2aa44f0431cc0ec1c41c4f

test:
  secret_key_base: 26e7ba731c4be73606a83ac6570d948bfc96648e283c530fcce22efd18938c2736dcc882f7d87faaa8a23a4cb0a63b6b78a9211ffb9ffc5df9fae7c6f9f735c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
